[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
rekthub = "rekthkL8cwpDX7BpsNKyJp72Xi99CT6bbLzx5UGt745"

[programs.localnet]
rekthub = "rekthkL8cwpDX7BpsNKyJp72Xi99CT6bbLzx5UGt745"

[programs.mainnet]
rekthub = "rekthB7rsdX7nCT8aQi977noT72AtkqVDWt1Y9VmZFG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
